package com.tamjid.course.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA Entity class representing a course in the database.
 *
 * This class maps directly to the TAMJID_COURSES table in Oracle:
 *
 *   TAMJID_COURSES
 *   ┌───────────────────┬──────────────┬─────────────────────────────────────────────┐
 *   │ Column            │ Java Field   │ Notes                                       │
 *   ├───────────────────┼──────────────┼─────────────────────────────────────────────┤
 *   │ COURSE_NO         │ courseNo     │ PK, auto-generated by S_TAMJID_COURSES seq  │
 *   │ COURSE_NAME       │ courseName   │ Name of the course                          │
 *   │ COURSE_DESCRIPTION│ courseDescription │ Description of the course              │
 *   │ COURSE_FEE        │ courseFee    │ Price to enroll                             │
 *   └───────────────────┴──────────────┴─────────────────────────────────────────────┘
 *
 * HOW IT CONNECTS:
 *   - CourseRepository uses this entity to perform CRUD operations on the database.
 *   - CourseServiceImpl converts between Course (this class) and CourseDTO before
 *     sending data to the controller.
 *   - JPA/Hibernate translates all the annotations below into actual SQL queries
 *     (INSERT, SELECT, UPDATE, DELETE) that run against the Oracle database.
 *
 * ABOUT THE ANNOTATIONS:
 *   @Entity         — Tells JPA that this class represents a table in the database.
 *   @Table          — Specifies the exact table name (if omitted, JPA uses the class name).
 *   @Id             — Marks courseNo as the primary key column.
 *   @GeneratedValue — Tells JPA how to generate the primary key value.
 *   @SequenceGenerator — Configures the Oracle sequence used for ID generation.
 *   @Column         — Maps a Java field to a specific database column name.
 *
 * Lombok annotations (@Getter, @Setter, @AllArgsConstructor, @NoArgsConstructor)
 * eliminate the need to write boilerplate getter/setter/constructor code manually.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "TAMJID_COURSES")
public class Course {

    /**
     * Primary key — mapped to COURSE_NO column.
     *
     * HOW ID GENERATION WORKS:
     * Oracle does not support AUTO_INCREMENT like MySQL. Instead, it uses SEQUENCES.
     * The @SequenceGenerator annotation below tells Hibernate:
     *   "Use the Oracle sequence named S_TAMJID_COURSES to generate unique IDs."
     *
     * allocationSize = 1 means Hibernate fetches one sequence value at a time.
     * (Higher values reduce DB round-trips but can cause gaps if the app restarts.)
     *
     * When a new Course is saved, Hibernate runs:
     *   1. SELECT S_TAMJID_COURSES.NEXTVAL FROM DUAL  → gets the next ID (e.g., 42)
     *   2. INSERT INTO TAMJID_COURSES (COURSE_NO, ...) VALUES (42, ...)
     */
    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "course_seq"
    )
    @SequenceGenerator(
            name = "course_seq",
            sequenceName = "S_TAMJID_COURSES",
            allocationSize = 1
    )
    @Column(name = "COURSE_NO")
    private Long courseNo;

    // Name of the course (e.g., "Spring Boot Basics").
    @Column(name = "COURSE_NAME")
    private String courseName;

    // A detailed description of what the course covers.
    @Column(name = "COURSE_DESCRIPTION")
    private String courseDescription;

    // The enrollment fee for this course.
    @Column(name = "COURSE_FEE")
    private Double courseFee;
}