package com.tamjid.course.dto;

/*
-- Oracle DDL (for reference — run these in your database before the app starts):

-- Create the sequence
CREATE SEQUENCE S_TAMJID_COURSES
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999
    NOCYCLE
    NOORDER;

-- Create the table
CREATE TABLE TAMJID_COURSES (
    course_no       NUMBER   PRIMARY KEY,
    course_name     VARCHAR2(100) NOT NULL,
    course_description     VARCHAR2(500),
    course_fee             NUMBER NOT NULL
);
*/


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) for the Course entity.
 *
 * WHAT IS A DTO AND WHY DO WE NEED IT?
 * A DTO is a plain object used to carry data between the backend and the frontend.
 * Instead of exposing the Course entity (which is tightly coupled to the database schema
 * via JPA annotations like @Entity, @Column, @SequenceGenerator, etc.), we send and
 * receive CourseDTO objects over HTTP.
 *
 * Benefits of using a DTO:
 *   1. Decoupling   — The frontend never sees database-specific details (column names,
 *                     sequence generators, table mappings).
 *   2. Flexibility  — We can add/remove/rename DTO fields without touching the database.
 *   3. Security     — We control exactly which fields are exposed to the client.
 *                     (e.g., we might hide internal audit fields from the response).
 *
 * HOW IT CONNECTS:
 *   Controller receives CourseDTO → Service converts it to Course entity → Repository saves to DB.
 *   Repository reads Course from DB → Service converts it to CourseDTO → Controller sends to frontend.
 *   The conversion logic lives in CourseServiceImpl (convertToDTO / convertToEntity methods).
 *
 * ABOUT THE ANNOTATIONS:
 *   @Getter  — Lombok generates a public get-method for every field (getCourseNo(), getCourseName(), etc.)
 *   @Setter  — Lombok generates a public set-method for every field (setCourseNo(), setCourseName(), etc.)
 *   @AllArgsConstructor — Lombok generates a constructor that takes ALL fields as parameters.
 *   @NoArgsConstructor  — We need a no-arg constructor so Spring/Jackson can create an empty
 *                          CourseDTO and then populate it from the incoming JSON.
 *                          (Lombok's @AllArgsConstructor alone would remove the default no-arg
 *                           constructor, so we add this one explicitly.)
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class CourseDTO {

    // Maps to TAMJID_COURSES.course_no — the primary key, auto-generated by Oracle sequence.
    private Long courseNo;

    // Maps to TAMJID_COURSES.course_name — the display name of the course (e.g., "Spring Boot Basics").
    private String courseName;

    // Maps to TAMJID_COURSES.course_description — a longer description of what the course covers.
    private String courseDescription;

    // Maps to TAMJID_COURSES.course_fee — the price a student pays to enroll.
    private Double courseFee;
}