package com.tamjid.course.service;

import java.util.List;

import com.tamjid.course.dto.CourseDTO;

/**
 * Service interface that defines the business operations for courses.
 *
 * WHY USE AN INTERFACE?
 * This is the "Service Layer" pattern. It separates business logic from the web layer
 * (controllers) and the data layer (repositories). The benefits are:
 *
 *   1. Testability  — You can mock this interface in unit tests for the controller
 *                     without needing a real database.
 *   2. Flexibility  — You can swap implementations (e.g., CourseServiceImpl for production,
 *                     a mock/in-memory implementation for tests) without changing the controller.
 *   3. Clean Architecture — Controllers depend on this interface, not on the implementation.
 *                           This keeps each layer focused on a single responsibility.
 *
 * HOW IT CONNECTS:
 *   CourseController depends on this interface (constructor injection).
 *   CourseServiceImpl implements this interface (the actual business logic).
 *   Spring wires them together automatically at startup.
 *
 * ALL METHODS WORK WITH CourseDTO (not Course entity) because:
 *   - The controller layer should never deal with JPA entities directly.
 *   - DTOs decouple the API contract from the database schema.
 *   - The DTO ↔ Entity conversion happens inside CourseServiceImpl.
 */
public interface CourseService {

    /**
     * Retrieves all courses from the database.
     * Used by the course catalog/listing page on the frontend.
     */
    List<CourseDTO> getAllCourses();

    /**
     * Retrieves a single course by its unique ID (course_no).
     *
     * @param id the primary key of the course
     * @return the course data as a DTO
     * @throws com.tamjid.course.exception.ResourceNotFoundException if no course exists with this ID
     */
    CourseDTO getCourseById(Long id);

    /**
     * Creates a new course in the database.
     * The courseNo is auto-generated by Oracle's sequence — it should NOT be in the DTO.
     *
     * @param dto the course data from the frontend (without courseNo)
     * @return the saved course including the generated courseNo
     */
    CourseDTO createCourse(CourseDTO dto);

    /**
     * Updates an existing course. Finds the course by ID, applies the new values,
     * and saves it back to the database.
     *
     * @param id  the primary key of the course to update
     * @param dto the new course data from the frontend
     * @return the updated course as a DTO
     * @throws com.tamjid.course.exception.ResourceNotFoundException if no course exists with this ID
     */
    CourseDTO updateCourse(Long id, CourseDTO dto);

    /**
     * Deletes a course from the database by its ID.
     *
     * @param id the primary key of the course to delete
     */
    void deleteCourse(Long id);
}